### ISSUE TITLE
personalit score

### ISSUE THREAD

**Issue by hhhhhy60** [Kali-Hac/ChatGPT-MBTI#1]
Hello! By reading the code, I found that the 16personality result seems not to be the final distribution, but a score. In your code, you calculate the final distribution (I-51, E-49) through your own logic. How is this calculation process determined?

**Comment by Kali-Hac** [comment]
Hi, the scores are actually computed following the logic of 16Personality website, which is manually inferred by repeated tests. You can try inputting the answers (which are generated by LLMs) into 16Personality website for manual validation. Thanks.
